on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: false
      artifact-retention-days:
        type: number
        default: 1
      artifact-name:
        type: string
        default: build
      deploy:
        type: boolean
        default: false
    secrets:
      CI_APP_ID:
        description: "GitHub App ID (numeric)"
        required: false
      CI_APP_PRIVATE_KEY:
        description: "GitHub App private key (PEM)"
        required: false        

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Generate GitHub App token (optional)
        id: app-token
        if: ${{ secrets.CI_APP_ID != '' && secrets.CI_APP_PRIVATE_KEY != '' }}
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.CI_APP_ID }}
          private_key: ${{ secrets.CI_APP_PRIVATE_KEY }}

      - name: Checkout (uses App token if available, else GITHUB_TOKEN)
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.145.0'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      # 1) Gate build
      - name: Install deps
        run: npm ci

      - name: Install postcss-cli (global)
        run: npm -g install postcss-cli

      - name: Hugo build (gate)
        run: hugo --minify --environment production

      - name: Upload build artifact (no deploy)
        if: ${{ inputs.upload-artifact && !inputs.deploy }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ./public
          retention-days: ${{ inputs.artifact-retention-days }}

      # 2) Detect range & propose tag
      - name: Detect range & propose tag
        if: ${{ inputs.deploy }}
        id: detect
        run: |
          set -euo pipefail
          DEFAULT_BRANCH='${{ github.event.repository.default_branch }}'
          echo "default_branch=${DEFAULT_BRANCH}" >> "$GITHUB_OUTPUT"
          git fetch origin "${DEFAULT_BRANCH}" --tags
          MAIN_REF="origin/${DEFAULT_BRANCH}"
          echo "main_ref=${MAIN_REF}" >> "$GITHUB_OUTPUT"
          MAIN_SHA=$(git rev-parse "${MAIN_REF}")
          PREV_TAG="$(git tag --sort=-creatordate | head -n1 || true)"
          if [ -z "${PREV_TAG}" ]; then
            if git rev-parse "${MAIN_SHA}^" >/dev/null 2>&1; then
              RANGE="${MAIN_SHA}^..${MAIN_SHA}"
            else
              RANGE="${MAIN_SHA}..${MAIN_SHA}"
            fi
          else
            RANGE="${PREV_TAG}..${MAIN_SHA}"
          fi
          echo "range=${RANGE}" >> "$GITHUB_OUTPUT"
          DATE_TAG=$(TZ=Europe/Zurich date +'%Y%m%d-%H%M')
          PROPOSED_TAG="${DATE_TAG}-${GITHUB_RUN_NUMBER}"
          echo "proposed_tag=${PROPOSED_TAG}" >> "$GITHUB_OUTPUT"

      # 3) Generate Latest-Changes (per year)
      - name: Update Latest-Changes pages (per year)
        if: ${{ inputs.deploy }}
        run: |
          set -euo pipefail
          chmod +x .github/scripts/update-latest-changes.sh
          .github/scripts/update-latest-changes.sh \
            "${{ steps.detect.outputs.proposed_tag }}" \
            "${{ steps.detect.outputs.main_ref }}" \
            "${{ steps.detect.outputs.range }}"

      # ✅ NEW: Prettier fix for generated files (runs only if files exist)
      - name: Prettier fix Latest-Changes
        if: ${{ inputs.deploy }}
        run: |
          set -euo pipefail
          if compgen -G "content/*/about/latest-changes/_index.md" > /dev/null; then
            npx -y prettier -w "content/*/about/latest-changes/_index.md"
          else
            echo "No latest-changes files to format."
          fi

      # 4) Commit Latest-Changes (after Prettier)
      - name: Commit Latest-Changes (protected branch)
        if: ${{ inputs.deploy }}
        env:
          COMMIT_NAME: ${{ steps.app-token.outputs.token && 'ci-push-bot[app]' || 'github-actions[bot]' }}
          COMMIT_EMAIL: ${{ steps.app-token.outputs.token && 'ci-push-bot[app]@users.noreply.github.com' || '41898282+github-actions[bot]@users.noreply.github.com' }}
        run: |
          set -euo pipefail
          git config user.name  "${COMMIT_NAME}"
          git config user.email "${COMMIT_EMAIL}"
          git add content/*/about/latest-changes/_index.md || true
          git commit -m "[skip ci] docs: update Latest-Changes for ${{ steps.detect.outputs.proposed_tag }}" || echo "Nothing to commit."
          git push origin "HEAD:${{ steps.detect.outputs.default_branch }}" || echo "Nothing to push."

      # 5) Rebuild (includes Latest-Changes)
      - name: Hugo rebuild (with updated Latest-Changes)
        if: ${{ inputs.deploy }}
        run: hugo --minify --environment production

      - name: Upload build artifact (with deploy)
        if: ${{ inputs.upload-artifact && inputs.deploy }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}-${{ steps.detect.outputs.proposed_tag }}
          path: ./public
          retention-days: ${{ inputs.artifact-retention-days }}

      # 6) Tag after commit & rebuild
      - name: Create Tag on default branch (Europe/Zurich)
        if: ${{ inputs.deploy }}
        id: tagstep
        env:
          COMMIT_NAME: ${{ steps.app-token.outputs.token && 'ci-push-bot[app]' || 'github-actions[bot]' }}
          COMMIT_EMAIL: ${{ steps.app-token.outputs.token && 'ci-push-bot[app]@users.noreply.github.com' || '41898282+github-actions[bot]@users.noreply.github.com' }}
        run: |
          set -euo pipefail
          DEFAULT_BRANCH="${{ steps.detect.outputs.default_branch }}"
          PROPOSED_TAG="${{ steps.detect.outputs.proposed_tag }}"
          git fetch origin "${DEFAULT_BRANCH}" --tags
          MAIN_REF="origin/${DEFAULT_BRANCH}"
          MAIN_SHA=$(git rev-parse "${MAIN_REF}")
          git config user.name  "${COMMIT_NAME}"
          git config user.email "${COMMIT_EMAIL}"
          git tag -a "${PROPOSED_TAG}" -m "Deploy $(TZ=Europe/Zurich date +'%Y-%m-%d %H:%M %Z') on ${DEFAULT_BRANCH} @ ${MAIN_SHA}" "${MAIN_SHA}"
          git push origin "${PROPOSED_TAG}"
          echo "tag_name=${PROPOSED_TAG}" >> "$GITHUB_OUTPUT"

      - name: Deploy to GitHub Pages
        if: ${{ inputs.deploy }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Check live site
        if: ${{ inputs.deploy }}
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://labs.it-ninjas.ch/
          follow-redirect: true
          max-attempts: 3
          retry-delay: 10s
