name: GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    uses: ./.github/workflows/build-deploy.yml
    secrets:
      CI_APP_ID: ${{ secrets.CI_APP_ID }}
      CI_APP_PRIVATE_KEY: ${{ secrets.CI_APP_PRIVATE_KEY }}    
    with:
      deploy: true