name: 'Test GH Pages'

on:
  push:
    branches:
      - feature/*  # Set a branch to deploy

jobs:
  test-compilation:
    uses: ./.github/workflows/build.yml
    with: 
      upload-artifact: true
      artifact-name: quality-check-build
